cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO14 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V       MSX TOPFOLDS #01       V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Use o utilitario "PRINTPAG.COM"
rem  ou  o  proprio   "MSX PageMaker
rem  DeLuxe"  para imprimir as pagi-
rem  nas "TOPFOLD1" e "TOPFOLD2" que
rem  estao contidas neste disco!
rem
