cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO 9 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V     GRAPHIC TEMPLATES #2     V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Prepare a impressora...
rem
pause
printpag ESCOLAR s
pause
printpag BALOES s
pause
printpag PRANCHA s
pause
printpag COLUNAS s
pause
printpag LIRIOS s
pause
printpag MINIROBO s
rem
rem  Cat logo impresso!
rem
