rem
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO 6 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   PRINT MASTER GALERIAS #1   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
pause
rem
dir GALERIA?.SHP
rem
PMEPSON
rem
rem  Cat logo impresso!
rem
