cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V     MSX CLIP-ART KIT 2.0     V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Bibliotecas:
rem
DIR *.SHP
CLIPSCAT
rem
rem  Cat logo impresso!
rem
