cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO18 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V DIGITIZED EROTIC PICTURES #1 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
pause
basic AUTOEXEC.BAS