cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO 8 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V     GRAPHIC TEMPLATES #1     V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Prepare a impressora...
rem
pause
printpag CONVITE s
pause
printpag COMIDAS s
pause
printpag MOLDURA s
pause
printpag JUKEBOX s
pause
printpag DESKTOP s
pause
printpag PAISAGEM s
rem
rem  Cat logo impresso!
rem
