rem
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO 4 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V    FIGURAS - PRINT MASTER    V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
pause
rem
dir FIGURAS?.SHP
rem
PMEPSON
rem
rem  Cat logo impresso!
rem
