cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO12 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V     GRAPHIC TEMPLATES #5     V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Prepare a impressora...
rem
pause
printpag USA-FLAG s
pause
printpag TINTEIRO s
pause
printpag PORTAL s
pause
printpag NEW-WAVE s
pause
printpag CADERNO s
pause
printpag GIZLOUSA s
rem
rem  Cat logo impresso!
rem
