rem MSX-C Ver.1.1 強化セット を まっさらなディスクにインストールするときに
rem 必要なファイル達とその所在

copy %1:EXLIB.TCO %2
copy %1:EXLIB.REL %2
copy %1:MCC.BAT %2
copy %1:BDOSZ.MAC %2
copy %1:CTYPE.H %2
copy %1:ETCLIB.H %2
copy %1:FILE.H %2
copy %1:NOREDIR.REL %2
copy %1:STRING.H %2
copy %1:TINYMAIN.REL %2
copy %1:GETS2.REL %2
copy %1:UTY.H %2
copy %1:JCTYPE.H %2
copy %1:CPPPP.COM %2
copy %1:JSTRING.H %2
copy %1:MSXCJP.BAT %2
copy %1:CURSESU.H %2
copy %1:JCURSES.H %2
copy %1:JCURSES.REL %2
copy %1:JCURSES.TCO %2
