cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO10 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V     GRAPHIC TEMPLATES #3     V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Prepare a impressora...
rem
pause
printpag AVISO s
pause
printpag BIRTHDAY s
pause
printpag BROADWAY s
pause
printpag CINEMA s
pause
printpag DINHEIRO s
pause
printpag QUADRO s
rem
rem  Cat logo impresso!
rem
