cls
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V MSX PAGEMAKER DeLuxe DISCO15 V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V       MSX TOPFOLDS #02       V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem  XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWY
rem  V   NEMESIS INFORMATICA LTDA   V
rem  ZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW[
rem
rem  Use o utilitario "PRINTPAG.COM"
rem  ou  o  proprio   "MSX PageMaker
rem  DeLuxe"  para imprimir as pagi-
rem  nas "TOPFOLD3" e "TOPFOLD4" que
rem  estao contidas neste disco!
rem
