To:                                                  CQ 3.24
          Sydex, Inc.
          P.O. Box 5700
          Eugene, OR  97405

                PRICES ARE VALID THROUGH DECEMBER 31, 1996

                          Name __________________________________
 
                       Company __________________________________

                    Department __________________________________

                       Street  __________________________________

      City, State, Zip/Country __________________________________

                               __________________________________


     Please complete the following:

    1.   Registration  fee.................................____________

         $25.00 CopyQM for personal non-commercial use.
         $75.00 CopyQM Plus for personal, commercial or multi-system
         (up to 25 systems) use.  Large sites should contact Sydex con-
         cerning special corporate licensing fees.

    2.   Shipping..........................................____________

         $2.50 for first-class postage inside the U.S.
         $3.50 for airmail postage to Canada
         $5.00 for international airmail.


    TOTAL of 1 and 2.......................................____________

    Please indicate payment method:

    Check/M.O. (U.S. funds ONLY) ___  VISA ___  MasterCard___

    Credit Card No._______________________________  Expires ________

    Signature______________________________________  Date ___________

    Check here ____ if you require 5.25" media.

We accept corporate purchase orders--please call Sydex for details.  You
can telephone your order to us at (800) 43-SYDEX (437 9339).  If you need
more information, call us at (541) 683-6033 or FAX us at (541) 683-1622.
